version: '3.8'

services:
  daemon:
    build:
      context: ./daemon
      args:
        - DAEMON_WORKDIR=/workspace/daemon
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
      - daemon_store:/workspace/daemon/node_modules
    init: true
    command: tail -F /dev/null
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: passw0rd!
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    ports:
      - 3306:3306

volumes:
  db_store:
  daemon_store: